### ISSUE TITLE
Turn events page into a collection

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/code-for-nashville.github.io#104]
- events page needs to be changed into html 
- individual events can be added as markdown files through a collection (see projects collection)

**Comment by rocketpastsix** [comment]
Ill take a look at this

**Comment by beck410** [comment]
champion! could you also take a look at the tut_edit branch  - i tried to turn the tutorial page into a collection with the markdown file you did but i'm getting an error when i try to view a single tutorial

**Comment by rocketpastsix** [comment]
Ill take a look at it. What does the error say?

**Comment by beck410** [comment]
It is trying to link to tut_title.html but it gives me a 404 error

**Comment by beck410** [comment]
the tutorials list page is working just not the single tutorial view

**Comment by rocketpastsix** [comment]
Ok Ill take a look at both and see what I can do.

**Comment by beck410** [comment]
Thanks :)

**Comment by rocketpastsix** [comment]
Hey, I was on vacation, and I know theres a new page design coming, is this still an issue or are we waiting?

**Comment by beck410** [comment]
We're currently building an app (brigade pulse - project x) that uses the cfa api to list projects, events etc of all the brigade in cfa - i think i'll use the same api to pull our events from meetup.com

how was Hawaii and the new brigade?

**Comment by rocketpastsix** [comment]
Hawaii was unbelievable and the new brigade has some great ideas. Im starting to reconnect after a week off grid so Ill get some details soon.
