### ISSUE TITLE
Open Budget Development Plan

### ISSUE THREAD

**Issue by topherhooper** [code-for-nashville/code-for-nashville.github.io#129]
# Purpose
1. allow for a platform for people to recommend uses for discretionary spending.
2. show historical budgets, where the money goes
3. show historical effects of budgets (if possible)
# Requirements
1. User input for spending
2. budget context
# Open Data Portal

https://data.nashville.gov/Metro-Government/Metro-Budget-To-Actual-Expenses-FY14-FY15-Official/s2um-p6bp
# Similar projects by other brigades
1. http://schoolbudget.phl.io/
2. http://openbudgetsac.org/
# Max's day one brain dump:

• budgeted to actual expenses. more than 6K row of detailed spending and budgeting information. - https://data.nashville.gov/Metro-Government/Metro-Budget-To-Actual-Expenses-FY14-FY15-Official/s2um-p6bp
• Tree Map Visualization -  http://bl.ocks.org/mbostock/4063582 -  instead of “Count” and “Size” to determine area, we could have “Budgeted Expenses" and “Actual Expense", and group by Department. Socrata actually supports generating these inside the platform - but we’ll have to clean the dollar amounts - they have “-“ for $0, and “()” for negative amounts (e.g. revenue instead of an expense).  Two things this type of visualization misses are direct comparison of how the budget grows between departments year to year, and direct comparison between actual and expected.  Spark lines (really sparse line graphs) and stacked bar graphs could show department by department budgeting, and we could provide a view that organizes budget changes by greatest absolute values changed (e.g. 10% increase, 25% decrease). We could also highlight new or destroyed departments or business units.
• Some existing Code For America budget projects - https://www.codeforamerica.org/brigade/projects?q=budget

Metropolitan Government of Nashville and Davidson County, Tennessee
Metro Budget To Actual Expenses (FY14 - FY15) - Official | Open Data Portal
Budget and actual expenses by fund, department, business unit and object account for the six tax supported funds.

Treemap
Mike Bostock’s Block 4063582

**Comment by enlore** [comment]
This sounds awesome, and is actually super relevant to my current interests as they relate to Metro and CfN.

**Comment by neolytics** [comment]
Good stuff ya'll.  I'll reach out to the public stakeholders and see if I can get them to sit down at another hack night.

**Comment by neolytics** [comment]
So one thing I've been thinking about and mentioned to @topherhooper is that it might make sense to begin entwining some of these new projects into the CfN.org site itself.

We already have a refined public facing website, so rather than continuing to generate one new website after another, it may make sense to begin extending our primary public face and adding new content there.

Food for thought.

**Comment by enlore** [comment]
For sure. I like the way, as an otherwise unrelated example, HashiCorp (the people who make Vagrant) use their primary domain as a portal to the individual domains of all their various products.

**Comment by mshenfield** [comment]
Copied this to a Trello card - I think it's a better spot for it.
