### ISSUE TITLE
Render Code of Conduct as Jekyll page instead of linking github README

### ISSUE THREAD

**Issue by combinatorist** [code-for-nashville/code-for-nashville.github.io#147]

**Comment by combinatorist** [comment]
Not to me. :(

If you navigate like so: http://www.codefornashville.org/ > About > Handbook > Code of Conduct (http://www.codefornashville.org/)

That will jump you to this section of the handbook (fine so far):

> **Code of Conduct**
> All participants are expected to adhere to the [Code for Nashville Code of Conduct](https://github.com/code-for-nashville/codeofconduct).

**But**, if you click the link, it takes you to https://github.com/code-for-nashville/codeofconduct, which is a github page. IMO, it would be better if **that** page, with the content of the code of conduct, looked like part of our website as was rendered (by Jekyll) similar to the handbook.

Does that distinction make sense? Do you agree that would be valuable?

**Comment by enlore** [comment]
My bad, I misunderstood the ask. I get what you're saying.

Leaving this open so we can target the CoC similarly to how the Handbook is being consumed/imported.

**Comment by CoreyAR** [comment]
The way this will work is  that we would pull download it and convert the markdown to html at runtime.

You can see how the handbook works here - https://github.com/code-for-nashville/code-for-nashville.github.io/blob/master/js/markdown.js
