### ISSUE TITLE
Expand info on projects

### ISSUE THREAD

**Issue by sciurus** [code-for-nashville/code-for-nashville.github.io#51]
Should say if project is active/inactive, and who is delivery lead for the project.

**Comment by vinbarnes** [comment]
@code-for-nashville/the-web-site-team does this still need to happen and/or is it still relevant? If so, is anyone available to tackle this?

Here is the listing on the web http://www.codefornashville.org/projects/ and the file behind it https://github.com/code-for-nashville/code-for-nashville.github.io/blob/master/projects.md

**Comment by neolytics** [comment]
I believe beck is on this as we speak.

**Comment by beck410** [comment]
@vinbarnes i plan to get it setup this week - will make a collection template in jekyll so we just have to add a new md file each time theres a new project rather than continually updating one file

**Comment by vinbarnes** [comment]
@beck410 great! :sparkles:

**Comment by neolytics** [comment]
Bump! Issue is still alive? @beck410

**Comment by beck410** [comment]
For now i'll close it - looking to open new issues for features and bugs people can contribute to
