### ISSUE TITLE
Form for Slack user signup

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/code-for-nashville.github.io#75]
@JamesNix 
@beck410 
@aaronwebb 

We need a form to manage signups for the slack channel.  Current incarnation only needs to send the email and name to an admin who can do the adding manually.

A v2 would send an email with an approve/deny button that a user can check and the invitation is handles automagically.

**Comment by beck410** [comment]
@JamesNix  do you remember what we used for the contact form? Simpleforms?

**Comment by jchapin** [comment]
Hello there, 
Thanks for using simpleform. 

You can read the instructions to setup your forms at: http://getsimpleform.com/instructions?api_token=[REMOVED]

I've got an API token for Simpleform, it may be in others hands as it went to webmaster@, but if you need it... I've got it.

**Comment by JamesNix** [comment]
@beck410 @jchapin Yep, it looks like we used simple form in contact_form.html and it also looks like the token is included there as well.
