### ISSUE TITLE
Update readme to reflect Jekyll install difficulties if not using vagrant

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/code-for-nashville.github.io#80]

**Comment by SondaSengupta** [comment]
Currently working on updating the readme for Jekyll install. I have not looked into Vagrant yet, but will soon.

**Comment by beck410** [comment]
closed?

**Comment by SondaSengupta** [comment]
Made the ReadMe Look more legible. As soon as someone checks, this thread is ready to close. #95

**Comment by SondaSengupta** [comment]
closed #95
