### ISSUE TITLE
Update team

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/code-for-nashville.github.io#85]
Lots of mostly inactives in there.

Would like to update roles and add active members

**Comment by neolytics** [comment]
Brigade Captain/Community Organizer - Jon Staples
Brigade Captain/Webmaster - Rebecca Cronin-Dixon
Delivery Lead - Jurnell Cockhren
Story Teller - Erin Page, Katye Russell
Operative - Alexandra Phillips
Developer Evangelists - Colby Dehart, Max Shenfield, James Nix
New Member Liaison - Sonda Sengupta
Community Liaison (?) - Joann Brooks

Community Partners:
John Wark - Nashville Software School
Yiaway Yeh - Metro Office of Innovation

**Comment by beck410** [comment]
I'll update this tomorrow

**Comment by neolytics** [comment]
Oh and forgot.

Brigade Captain Emeritus - John Chapin

**Comment by beck410** [comment]
@neolytics done - can you check for spelling errors
