### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/code-for-nashville.github.io#86]
A blog, a blog, my kingdom for a blog!

Be it ghost or wordpress, let us find a blog!

**Comment by neolytics** [comment]
@jcockhren

**Comment by beck410** [comment]
for now i'll include the current blog in the new site design

**Comment by neolytics** [comment]
@jcockhren Can you give us updates on the status/deployment of the ghost blog?  Obviously there is a repo, but I know very little about it.

**Comment by neolytics** [comment]
@beck410 How do you feel about removing the current blog link?  It is a bit depressing to see content that hasn't been updated in 6 months.  I don't think it reflects well on us.

**Comment by beck410** [comment]
blog link removed
