### ISSUE TITLE
Github issues/milestones on How To Help Page

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/code-for-nashville.github.io#88]
List issues and milestones for each project on website under 'How Can I Help' page. Could include a brief description for accepting an issue by adding yourself as the assignee. That way everyone knows the issue is being handled and by who. 

see @jchapin github repo dashboards_and_reports for usage of Github API

**Comment by beck410** [comment]
http://codeforamerica.org/api/

The heavy work has already been done for us

**Comment by SondaSengupta** [comment]
I made the initial concept of this on the helpage branch #97 but Travis gives build errors.
