### ISSUE TITLE
New Header Image

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/code-for-nashville.github.io#89]
New header image needed of Nashville skyline or downtown. Must be royalty free etc.

**Comment by beck410** [comment]
@neolytics any chance we have a few dollars to buy a stock image? (if not i'll donate it :wink: )

**Comment by jchapin** [comment]
@beck410, the original CfN skyline image was Creative Commons Attribution licensed, but it may be time to swap it out for a new one.
