### ISSUE TITLE
Projects page - new layout

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/code-for-nashville.github.io#92]
Need new layout for projects page with more details for projects, current people working on project, needs/requirements etc

Separate current projects and proposed projects

**Comment by beck410** [comment]
may have someone willing to work on this page using the CFA API

**Comment by beck410** [comment]
waiting on new design by @StevenPrescott

**Comment by StevenPrescott** [comment]
Just saw this. Working on it today.
