### ISSUE TITLE
Sponsorship Page?

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/code-for-nashville.github.io#93]
What about having a sponsorship page that lists our community partners/sponsors and how to become a sponsor/donate

**Comment by neolytics** [comment]
Absolutely.

**Comment by beck410** [comment]
Once we figure out donor v sponsor i'll put a page up

**Comment by neolytics** [comment]
Donors and Community Partners are the current terms.  Sponsors implies a level of corporate marketing that we are not really interested in engaging in.
