### ISSUE TITLE
Tutorials Page

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/code-for-nashville.github.io#96]
Create a tutorials page with the vagrant tutorial added

**Comment by rocketpastsix** [comment]
do you still need help with this? Im with Code For Atlanta but can gladly give help.

**Comment by beck410** [comment]
Hi @rocketpastsix 
That would be awesome! we are currently undergoing a new redesign but would be great to have the structure set up for this page and up and running  - we currently have 2 tutorials that need to go up.

Let me know if you would like to take this on and i'll add you as a contributor :)

Thanks so much for your help :)

**Comment by rocketpastsix** [comment]
Seems pretty straight forward, I think I forked the repo already, so Ill create a dev branch and get to work.

**Comment by beck410** [comment]
you're awesome @rocketpastsix

**Comment by rocketpastsix** [comment]
I have some time tonight to work on this. Will you be around tonight in case I need anything? I dont think I will, but just in case. 

Also, I have yet to hear about Atlanta's Civic Hack day, so unless something changes this week, Im thinking of signing up for yours if thats cool and making the drive up there.

**Comment by beck410** [comment]
@rocketpastsix  we'd love to have you attend our Civic hack day! It's looking to be a lot of fun

Yep i'll be around - feel free to join our slack channel - you can sign up on the site - i'm usually always on there as i use it for work a lot - otherwise just email me and i'll make sure i get back to you quickly :)

**Comment by rocketpastsix** [comment]
Sweet! Ill get on slack in a bit, and get in that room, would be cool just to hang out and get to know everyone.

**Comment by rocketpastsix** [comment]
I made a pull request if you want to check it out.

**Comment by beck410** [comment]
Turning tuts page into a collection and adding Matt's md file- @colbydehart can you pull down the tut_edit branch and see where i'm going wrong - more info in cfn website slack channel
